import { Hono } from 'hono';
import { handle } from 'hono/vercel';

// Stub so Vercel registers this as a serverless function route pre-build.
// At runtime, api/index.js (generated by `npm run build:api`) takes precedence.
const app = new Hono().basePath('/api');
export default handle(app);
